let moon = document.querySelector(".moonIcon");
let label = document.querySelectorAll("label");
let buttonsContainer = document.querySelector(".buttonsContainer");
let linearBoxDiv = document.querySelector(".linearBoxDiv");
let cancelBtn = document.querySelector(".cancelBtn");
let main = document.querySelector("main");
let addNewItem = document.querySelector(".addNewItem");
let input = document.querySelectorAll("input");
let invoiceView = document.querySelector(".invoiceView");
let statusBox = document.querySelector(".statusBox");
let invoiceSummary = document.querySelector(".invoiceSummary");
let invoiceTitle = document.querySelector(".invoiceTitle");
let invoiceDate = document.querySelector(".invoiceDate");
let paymentTerms = document.querySelector(".paymentTerms");
let clientName = document.querySelector(".clientName");
let clientEmail = document.querySelector(".clientEmail");
let itemName = document.querySelectorAll(".itemName");
let total = document.querySelectorAll(".total");
let orderSummaryBox = document.querySelectorAll(".orderSummaryBox");
let orderTotalBox = document.querySelector(".orderTotalBox");
let buttonsContainer2 = document.querySelector(".buttonsContainer2");
moon.addEventListener("click", () => {
  input.forEach((el) => el.classList.toggle("input-dark-mode"));
  label.forEach((el) => el.classList.toggle("label-dark-mode"));
  main.classList.toggle("dark-mode");
  addNewItem.classList.toggle("dark-mode");
  addNewItem.classList.toggle("dark-mode-dark-blue");
  addNewItem.style.backgroundColor = "#252945";
  linearBoxDiv.classList.toggle("dark-mode");
  linearBoxDiv.style.border = "0";
  buttonsContainer.classList.toggle("invoice-dark-mode");
  cancelBtn.style.backgroundColor = "#252945";
  invoiceView.classList.toggle("dark-mode");
  statusBox.classList.toggle("invoice-dark-mode");
  invoiceSummary.classList.toggle("invoice-dark-mode");
  invoiceSummary.classList.toggle("dark-mode-light");
  invoiceTitle.classList.toggle("dark-mode-white");
  invoiceDate.classList.toggle("dark-mode-white");
  paymentTerms.classList.toggle("dark-mode-white");
  orderSummaryBox.forEach((el) => el.classList.toggle("input-dark-mode"));
  clientName.classList.toggle("dark-mode-white");
  itemName.forEach((el) => el.classList.toggle("dark-mode-white"));
  total.forEach((el) => el.classList.toggle("dark-mode-white"));
  clientEmail.classList.toggle("dark-mode-white");
  orderTotalBox.classList.toggle("dark-mode-dark");
  buttonsContainer2.classList.toggle("invoice-dark-mode");
});
