let moon = document.querySelector(".moonIcon");
let label = document.querySelectorAll("label");
let buttonsContainer = document.querySelector(".buttonsContainer");
let linearBoxDiv = document.querySelector(".linearBoxDiv");
let cancelBtn = document.querySelector(".cancelBtn");
let main = document.querySelector("main");
let addNewItem = document.querySelector(".addNewItem");
let input = document.querySelectorAll("input");
let invoiceView = document.querySelector(".invoiceView");
let statusBox = document.querySelector(".statusBox");
let invoiceSummary = document.querySelector(".invoiceSummary");
let invoiceTitle = document.querySelector(".invoiceTitle");
let invoiceDate = document.querySelector(".invoiceDate");
let paymentTerms = document.querySelector(".paymentTerms");
let clientName = document.querySelector(".clientName");
let clientEmail = document.querySelector(".clientEmail");
let itemName = document.querySelector(".itemName");
let total = document.querySelector(".total");
moon.addEventListener("click", () => {
  input.forEach((el) => el.classList.toggle("input-dark-mode"));
  label.forEach((el) => el.classList.toggle("label-dark-mode"));
  main.classList.toggle("dark-mode");
  addNewItem.classList.toggle("dark-mode");
  addNewItem.style.color = "#7e88c3";
  addNewItem.style.backgroundColor = "#252945";
  linearBoxDiv.classList.toggle("dark-mode");
  linearBoxDiv.style.border = "0";
  buttonsContainer.style.backgroundColor = "#1E2139";
  cancelBtn.style.backgroundColor = "#252945";
  invoiceView.classList.toggle("dark-mode");
  statusBox.classList.toggle("invoice-dark-mode");
  invoiceSummary.classList.toggle("invoice-dark-mode");
  invoiceSummary.classList.toggle("dark-mode-light");
  invoiceTitle.classList.toggle("dark-mode-white");
  invoiceDate.classList.toggle("dark-mode-white");
  paymentTerms.classList.toggle("dark-mode-white");
  clientName.classList.toggle("dark-mode-white");
  itemName.classList.toggle("dark-mode-white");
  total.classList.toggle("dark-mode-white");
  clientEmail.classList.toggle("dark-mode-white");
});
